/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import RegistraEventi.*;
import gestionefile.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import oggetti.*;

public class AreaOperatore extends javax.swing.JFrame {

    GestisciOperatori go = new GestisciOperatori();
    GestisciCentri gc = new GestisciCentri();
    ArrayList<OperatoriClimatici> op = new ArrayList<>();
    ArrayList<CentroMonitoraggio> cm = new ArrayList<>();
    ArrayList<ParametriClimatici> pm = new ArrayList<>();
    LoggerEventi logger = LoggerEventi.getInstance();
    OperatoriClimatici passato;
    String centroOp;
    String sceltaPaese = null;
    String nomePaese = null;
    String cc = null;
    
    public AreaOperatore(){
        initComponents();
    }
    
    public AreaOperatore(int id, String password){
        initComponents();
        addWindowListener(new Chiusura());
        passato = new OperatoriClimatici(id, password);
        
        if(go.login(passato)){
            passato = go.getOperatore();
            OperatoriClimatici operatore = go.getOperatore();
            jLabel2.setText("OPERATORE " +passato.getUserID());
            try {
                if(go.haCentro(passato)){
                    titReg.setVisible(false);
                    registraCentro.setVisible(false);
                    scegliCentro.setVisible(false);
                    out1.setText("Centro " +passato.getCentroM());
                    centroOp = passato.getCentroM();
                    try {
                        ResultSet set = gc.trovaAreeMonitorate(centroOp);
                        ArrayList<String> names = new ArrayList<>();

                        while (set.next()) {
                            names.add(set.getString("asciipaese") + " " + set.getString("codicestato"));
                        }

                        names.add(0, "nessun paese");

                        String[] namesArray = names.toArray(new String[0]);
                        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(namesArray);
                        scelta.setModel(model);
                    } catch (SQLException ex) {
                        Logger.getLogger(AreaOperatore.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    out2.setVisible(true);
                }else{
                    titReg.setVisible(true);
                    registraCentro.setVisible(true);
                    scegliCentro.setVisible(true);
                    scelta.setVisible(false);
                    cercaParam.setVisible(false);
                    out1.setVisible(false);
                    out2.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AreaOperatore.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        registraCentro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        out1 = new javax.swing.JLabel();
        titReg = new javax.swing.JLabel();
        out2 = new javax.swing.JLabel();
        scegliCentro = new javax.swing.JButton();
        scelta = new javax.swing.JComboBox<>();
        cercaParam = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Indietro");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 254, -1, -1));

        registraCentro.setText("Registra");
        registraCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraCentroActionPerformed(evt);
            }
        });
        getContentPane().add(registraCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titolo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titolo.setText("AREA OPERATORE");
        jPanel1.add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        out1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(out1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 31));

        titReg.setText("REGISTRA IL CENTRO");
        jPanel1.add(titReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 159, -1, 18));

        out2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(out2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 100, 26));

        scegliCentro.setText("Scegli");
        scegliCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliCentroActionPerformed(evt);
            }
        });
        jPanel1.add(scegliCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        scelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceltaActionPerformed(evt);
            }
        });
        jPanel1.add(scelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, 30));

        cercaParam.setText("Cerca");
        cercaParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaParamActionPerformed(evt);
            }
        });
        jPanel1.add(cercaParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 160, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("OPERATORE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 24));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Login l = new Login();
        l.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        l.setVisible(true); 
    }//GEN-LAST:event_backActionPerformed

    private void registraCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraCentroActionPerformed
        RegistraCentro rc = new RegistraCentro(passato.getUserID(), passato.getPassword());
        rc.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        rc.setVisible(true);
    }//GEN-LAST:event_registraCentroActionPerformed

    private void cercaParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaParamActionPerformed
        out2.setText("");
        Paese p;
        
        if(sceltaPaese != null && sceltaPaese != "nessun paese"){
            p = gc.trovaArea(nomePaese, cc, centroOp);
            Parametri pa = new Parametri(passato.getUserID(), passato.getPassword(), centroOp, p);
            pa.setLocation(this.getX(), this.getY());
            this.setVisible(false); 
            pa.setVisible(true);
        }else
            out2.setText("Invalido");
    }//GEN-LAST:event_cercaParamActionPerformed

    private void scegliCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliCentroActionPerformed
        ScegliCentro sc = new ScegliCentro(passato.getUserID(), passato.getPassword());
        sc.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        sc.setVisible(true);
    }//GEN-LAST:event_scegliCentroActionPerformed

    private void sceltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceltaActionPerformed
        sceltaPaese = (String) scelta.getSelectedItem();
        String[] parts = sceltaPaese.split(" ");
        nomePaese = parts[0];
        cc = parts[1];
    }//GEN-LAST:event_sceltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaOperatore().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cercaParam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel out1;
    private javax.swing.JLabel out2;
    private javax.swing.JButton registraCentro;
    private javax.swing.JButton scegliCentro;
    private javax.swing.JComboBox<String> scelta;
    private javax.swing.JLabel titReg;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
