/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import gestionefile.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import oggetti.*;

/**
 *
 * @author massi
 */
public class ScegliCentro extends javax.swing.JFrame {

    GestisciCentri gc = new GestisciCentri();
    GestisciOperatori go = new GestisciOperatori();
    OperatoriClimatici passato;
    String sceltaCentro = null;
    
    public ScegliCentro() {
        initComponents();
    }
    
    public ScegliCentro(int id, String pass){
        try {
            initComponents();
            passato = new OperatoriClimatici(id, pass);
            ResultSet set = gc.leggiCentri();
            ArrayList<String> names = new ArrayList<>();
            
            while (set.next()) {
                names.add(set.getString("nomeCentro"));
            }
            
            names.add(0, "nessun centro");
            
            String[] namesArray = names.toArray(new String[0]);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(namesArray);
            scelta.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(ScegliCentro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        scelta = new javax.swing.JComboBox<>();
        scegli = new javax.swing.JButton();
        out = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Indietro");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, -1, -1));

        scelta.setName(""); // NOI18N
        scelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceltaActionPerformed(evt);
            }
        });
        getContentPane().add(scelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 89, 113, -1));

        scegli.setText("Scegli");
        scegli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliActionPerformed(evt);
            }
        });
        getContentPane().add(scegli, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 89, 84, -1));

        out.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 141, 75, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("SCEGLI CENTRO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 6, -1, 43));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 410, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        AreaOperatore ao = new AreaOperatore(passato.getUserID(), passato.getPassword());
        ao.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        ao.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void sceltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceltaActionPerformed
        out.setText("");
        sceltaCentro = (String) scelta.getSelectedItem();
    }//GEN-LAST:event_sceltaActionPerformed

    private void scegliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliActionPerformed
        try {
            if(sceltaCentro != null){
                if(!sceltaCentro.equals("nessun centro")){ 
                    go.setCentro(passato, sceltaCentro);
                    AreaOperatore ao = new AreaOperatore(passato.getUserID(), passato.getPassword());
                    ao.setLocation(this.getX(), this.getY());
                    this.setVisible(false);
                    ao.setVisible(true);
                }else
                    out.setText("Invalido");
            }else
                    out.setText("Invalido");
                
        } catch (SQLException ex) {
            Logger.getLogger(ScegliCentro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_scegliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScegliCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScegliCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScegliCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScegliCentro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScegliCentro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel out;
    private javax.swing.JButton scegli;
    private javax.swing.JComboBox<String> scelta;
    // End of variables declaration//GEN-END:variables
}
