/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import RegistraEventi.*;
import gestionefile.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oggetti.*;

/**
 *
 * @author hew15bc502nl
 */
public class StampaParametri extends javax.swing.JFrame {

    GestisciParametri gParam = new GestisciParametri();
    GestisciPaesi gPaesi = new GestisciPaesi();
    DefaultTableModel model1, model2, model3;
    
    public StampaParametri() {
        initComponents();
        addWindowListener(new Chiusura());
        model1 = (DefaultTableModel) tabella1.getModel(); 
        model1.setRowCount(0);
        model2 = (DefaultTableModel) tabella2.getModel(); 
        model2.setRowCount(0);
        model3 = (DefaultTableModel) tabella3.getModel(); 
        model3.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ric1 = new javax.swing.JTextField();
        ric2 = new javax.swing.JTextField();
        cerca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabella1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabella2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabella3 = new javax.swing.JTable();
        out = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("STAMPA PARAMETRI");

        back.setText("Indietro");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel2.setText("Inserisci Area");

        cerca.setText("Cerca");
        cerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaActionPerformed(evt);
            }
        });

        tabella1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Centro", "Paese", "Codice", "Latitudine", "Longitudine", "Data", "Vento", "Umidità", "Pressione", "Temperatura", "Precipitazioni", "Altitudine", "Massa", "nota1", "nota2", "nota3", "nota4", "nota5", "nota6", "nota7"
            }
        ));
        jScrollPane1.setViewportView(tabella1);

        tabella2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vento", "Umidità", "Pressione", "Temperatura", "Precipitazione", "Altitudine", "Massa"
            }
        ));
        jScrollPane2.setViewportView(tabella2);

        tabella3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vento", "Umidità", "Pressione", "Temperatura", "Precipitazioni", "Altitudine", "Massa"
            }
        ));
        jScrollPane3.setViewportView(tabella3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ric2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ric1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cerca, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel2)))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(ric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cerca)
                        .addGap(32, 32, 32)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(back))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Cittadino cit = new Cittadino();
        cit.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        cit.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void cercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaActionPerformed
        ResultSet set = null;
        ArrayList<ParametriClimatici> parametri;
        out.setText("");
        String nome = ric1.getText();
        String codice = ric2.getText();

        Paese paese = gPaesi.ricercaNomeCC(nome, codice);
        if(paese != null){
            parametri = gParam.ricercaParametriArea(paese);
            if(parametri.isEmpty())
                out.setText("Nessuna rilevazione");
            double[] media;
            media = gParam.getMedie();
            int[] moda;
            moda = gParam.getModa();

            //ar = gp.ricercaParametriArea(nome, codice);
            model1.setRowCount(0);
            model2.setRowCount(0);
            model3.setRowCount(0);

            Object dati[] = new Object[20];
            for(int i=0; i<parametri.size(); i++){
                dati[0] = parametri.get(i).getNomeC();
                dati[1] = parametri.get(i).getData();
                dati[5] = parametri.get(i).getData();
                dati[6] = parametri.get(i).getVento();
                dati[7] = parametri.get(i).getUmidita();
                dati[8] = parametri.get(i).getPressione();
                dati[9] = parametri.get(i).getTemperatura();
                dati[10] = parametri.get(i).getPrecipitazioni();
                dati[11] = parametri.get(i).getAltitudine();
                dati[12] = parametri.get(i).getMassa();
                dati[13] = parametri.get(i).getNoteV();
                dati[14] = parametri.get(i).getNoteU();
                dati[15] = parametri.get(i).getNotePres();
                dati[16] = parametri.get(i).getNoteT();
                dati[17] = parametri.get(i).getNotePrec();
                dati[18] = parametri.get(i).getNoteA();
                dati[19] = parametri.get(i).getNoteM();

                model1.addRow(dati);
            }

            Object dati1[] = new Object[7];
            dati1[0] = media[0];
            dati1[1] = media[1];
            dati1[2] = media[2];
            dati1[3] = media[3];
            dati1[4] = media[4];
            dati1[5] = media[5];
            dati1[6] = media[6];

            if(!parametri.isEmpty())
                model2.addRow(dati1);

            Object dati2[] = new Object[7];
            dati2[0] = moda[0];
            dati2[1] = moda[1];
            dati2[2] = moda[2];
            dati2[3] = moda[3];
            dati2[4] = moda[4];
            dati2[5] = moda[5];
            dati2[6] = moda[6]; 

            if(!parametri.isEmpty())
                model3.addRow(dati1);
        }else
            out.setText("Nessun paese trovato");
        
    }//GEN-LAST:event_cercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StampaParametri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StampaParametri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StampaParametri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StampaParametri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StampaParametri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cerca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel out;
    private javax.swing.JTextField ric1;
    private javax.swing.JTextField ric2;
    private javax.swing.JTable tabella1;
    private javax.swing.JTable tabella2;
    private javax.swing.JTable tabella3;
    // End of variables declaration//GEN-END:variables
}
