/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.frame;

import client.registraeventi.Chiusura;
import commons.oggetti.Operatore;
import commons.oggetti.PuntoInteresse;

import java.rmi.RemoteException;

import commons.servizio.Autenticazione;
import commons.servizio.GestioneCentriMonitoraggio;
import server.servizio.GestoreCentriMonitoraggio;
import server.servizio.autenticazione.Autenticatore;

public class AreaOperatore extends javax.swing.JFrame {
    Autenticazione autenticazione = new Autenticatore();
    GestioneCentriMonitoraggio gestioneCentriMonitoraggio = new GestoreCentriMonitoraggio();
    String nomeCentroMonitoraggioOperatore;
    Operatore operatorePassato;
    
    public AreaOperatore(){
        initComponents();
    }
    
    public AreaOperatore(int id, String password){
        initComponents();
        addWindowListener(new Chiusura());
        operatorePassato = new Operatore(id, password);

        //TODO rmi client
        try {
            if (autenticazione.login(operatorePassato.getUsername(), operatorePassato.getPassword()) == true) {
                operatorePassato = autenticazione.ottieniOperatoreAutenticato();
                jLabel2.setText("OPERATORE " + operatorePassato.getUsername());

                if (operatorePassato.getIdCentroMonitoraggio() == null ) {
                    titReg.setVisible(true);
                    centro.setVisible(true);
                    jLabel1.setVisible(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false);
                    CCPP.setVisible(false);
                    nomePP.setVisible(false);
                    cercaParam.setVisible(false);
                    out1.setVisible(false);
                    out2.setVisible(false);

                } else {
                    titReg.setVisible(false);
                    centro.setVisible(false);
                    out1.setText("Centro " + operatorePassato.getIdCentroMonitoraggio());
                    nomeCentroMonitoraggioOperatore = operatorePassato.getIdCentroMonitoraggio();
                    out2.setVisible(true);
                }

            }
        } catch(RemoteException ex) {
            System.err.println("Errore RMI");
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        centro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CCPP = new javax.swing.JTextField();
        nomePP = new javax.swing.JTextField();
        cercaParam = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        out1 = new javax.swing.JLabel();
        titReg = new javax.swing.JLabel();
        out2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Indietro");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 254, -1, -1));

        centro.setText("Registra");
        centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centroActionPerformed(evt);
            }
        });
        getContentPane().add(centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("OPERATORE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 79, -1, 24));

        CCPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCPPActionPerformed(evt);
            }
        });
        getContentPane().add(CCPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 214, 73, -1));
        getContentPane().add(nomePP, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 180, 73, -1));

        cercaParam.setText("Cerca");
        cercaParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaParamActionPerformed(evt);
            }
        });
        getContentPane().add(cercaParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 254, -1, -1));

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 183, 56, -1));

        jLabel4.setText("Codice");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 217, 56, -1));

        jLabel1.setText("Cerca Paese");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 158, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        titolo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titolo.setText("AREA OPERATORE");

        out1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        titReg.setText("REGISTRA IL CENTRO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(titReg)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titolo)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(out1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(out2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titolo)
                .addGap(37, 37, 37)
                .addComponent(out1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titReg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(out2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Login l = new Login();
        l.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        l.setVisible(true); 
    }//GEN-LAST:event_backActionPerformed

    private void centroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centroActionPerformed
        RegistraCentro rc = new RegistraCentro(operatorePassato.getUsername(), operatorePassato.getPassword());
        rc.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        rc.setVisible(true);
    }//GEN-LAST:event_centroActionPerformed

    private void cercaParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaParamActionPerformed
        out2.setText("");

        PuntoInteresse puntoInteresse = null;
        PuntoInteresse[] elencoPuntiInteresse = null;

        //TODO rmi client
        try {
            elencoPuntiInteresse = gestioneCentriMonitoraggio.ottieniAreeAssociate(nomeCentroMonitoraggioOperatore);
        } catch(RemoteException ex) {
            System.err.println("Errore RMI");
            System.exit(1);
        }

        if(elencoPuntiInteresse == null) {
            out2.setText("Non ci sono punti di interesse associati al centro");
            return;
        }

        for(PuntoInteresse puntoInteresseTemp : elencoPuntiInteresse)
            if(puntoInteresseTemp.getNomePuntoInteresseASCII().equalsIgnoreCase(nomePP.getText()) && puntoInteresseTemp.getCodiceNazione().equalsIgnoreCase(CCPP.getText()))
                puntoInteresse = puntoInteresseTemp;

        if(puntoInteresse == null) {
            out2.setText("Punto di interesse non trovato");
            return;
        }

        Parametri pa = new Parametri(operatorePassato.getUsername(), operatorePassato.getPassword(), nomeCentroMonitoraggioOperatore, puntoInteresse);
        pa.setLocation(this.getX(), this.getY());
        this.setVisible(false);
        pa.setVisible(true);

    }//GEN-LAST:event_cercaParamActionPerformed

    private void CCPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaOperatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaOperatore().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCPP;
    private javax.swing.JButton back;
    private javax.swing.JButton centro;
    private javax.swing.JButton cercaParam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomePP;
    private javax.swing.JLabel out1;
    private javax.swing.JLabel out2;
    private javax.swing.JLabel titReg;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
