INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AF','Afghanistan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AX','Åland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AL','Albania');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('DZ','Algeria');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AS','American Samoa');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AD','Andorra');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AO','Angola');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AI','Anguilla');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AQ','Antartica');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AG','Antigua and Barbuda');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AR','Argentina');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AM','Armenia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AW','Aruba');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AU','Australia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AT','Austria');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AZ','Azerbaijan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BS','Bahamas');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BH','Bahrain');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BD','Bangladesh');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BB','Barbados');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BY','Belarus');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BE','Belgium');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BZ','Belize');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BJ','Benin');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BM','Bermuda');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BT','Bhutan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BO','Bolivia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BA','Bosnia and Herzegovina');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BW','Botswana');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BR','Brazil');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VG','British Virgin Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BN','Brunei Darussalam');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BG','Bulgaria');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BF','Burkina Faso');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BI','Burundi');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KH','Cambodia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CM','Cameroon');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CA','Canada');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CV','Cape Verde');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BQ','Caribbean Netherlands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KY','Cayman Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CF','Central African Republic');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TD','Chad');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CL','Chile');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CN','China');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CX','Christmas Island');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CO','Colombia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KM','Comoros');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CG','Congo');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CD','Congo - Democratic Republic of the');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CK','Cook Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CR','Costa Rica');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CI','Côte d''Ivoire');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('HR','Croatia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CU','Cuba');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CW','Curaçao');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CY','Cyprus');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CZ','Czech Republic');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('DK','Denmark');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('DJ','Djibouti');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('DM','Dominica');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('DO','Dominican Republic');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('EC','Ecuador');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('EG','Egypt');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SV','El Salvador');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GQ','Equatorial Guinea');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ER','Eritrea');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('EE','Estonia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ET','Ethiopia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('FO','Faeroe Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('FM','Federated States of Micronesia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('FJ','Fiji');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('FI','Finland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('FR','France');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GF','French Guiana');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PF','French Polynesia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TF','French Southern and Antarctic Lands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GA','Gabon');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GM','Gambia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GE','Georgia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('DE','Germany');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GH','Ghana');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GI','Gibraltar');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GR','Greece');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GL','Greenland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GD','Grenada');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GP','Guadeloupe');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GU','Guam');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GT','Guatemala');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GG','Guernsey');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GN','Guinea');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GW','Guinea-Bissau');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GY','Guyana');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('HT','Haiti');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('HN','Honduras');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('HK','Hong Kong - China');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('HU','Hungary');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IS','Iceland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IN','India');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ID','Indonesia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IR','Iran - Islamic Rep. of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IQ','Iraq');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IE','Ireland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IM','Isle of Man');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IL','Israel');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('IT','Italy');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('JM','Jamaica');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('JP','Japan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('JE','Jersey');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('JO','Jordan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KZ','Kazakhstan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KE','Kenya');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KI','Kiribati');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KP','Korea - Dem. People''s Rep. of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KR','Korea - Republic of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('XK','Kosovo');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KW','Kuwait');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KG','Kyrgyzstan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LA','Lao People''s Dem. Rep.');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LV','Latvia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LB','Lebanon');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LS','Lesotho');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LR','Liberia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LY','Libyan Arab Jamahiriya');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LI','Liechtenstein');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LT','Lithuania');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LU','Luxembourg');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MO','Macau - China');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MK','Macedonia - The former Yugoslav Rep. of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MG','Madagascar');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MW','Malawi');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MY','Malaysia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MV','Maldives');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ML','Mali');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MT','Malta');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MH','Marshall Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MQ','Martinique');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MR','Mauritania');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MU','Mauritius');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('YT','Mayotte');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MX','Mexico');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MD','Moldova - Republic of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MC','Monaco');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MN','Mongolia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ME','Montenegro');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MS','Montserrat');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MA','Morocco');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MZ','Mozambique');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MM','Myanmar');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NA','Namibia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NR','Nauru');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NP','Nepal');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NL','Netherlands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NC','New Caledonia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NZ','New Zealand');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NI','Nicaragua');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NE','Niger');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NG','Nigeria');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NU','Niue');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NF','Norfolk Island');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MP','Northern Mariana Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('NO','Norway');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('OM','Oman');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PK','Pakistan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PW','Palau');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PA','Panama');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PG','Papua New Guinea');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PY','Paraguay');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PE','Peru');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PH','Philippines');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PN','Pitcairn Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PL','Poland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PT','Portugal');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PR','Puerto Rico');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('QA','Qatar');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('RE','Réunion');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('RO','Romania');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('RU','Russian Federation');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('RW','Rwanda');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('BL','Saint Barthélemy');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SH','Saint Helena');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('KN','Saint Kitts and Nevis');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LC','Saint Lucia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('MF','Saint Martin');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PM','Saint Pierre and Miquelon');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VC','Saint Vincent and the Grenadines');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('WS','Samoa');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SM','San Marino');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ST','Sao Tome and Principe');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SA','Saudi Arabia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SN','Senegal');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('RS','Serbia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SC','Seychelles');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SL','Sierra Leone');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SG','Singapore');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SX','Sint Maarten');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SK','Slovakia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SI','Slovenia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SB','Solomon Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SO','Somalia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ZA','South Africa');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GS','South Georgia and the South Sandwich Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SS','South Sudan - The Republic of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ES','Spain');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('LK','Sri Lanka');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SD','Sudan - The Republic of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SR','Suriname');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SJ','Svalbard');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SZ','Swaziland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SE','Sweden');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('CH','Switzerland');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('SY','Syrian Arab Republic');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TW','Taiwan - China');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TJ','Tajikistan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TZ','Tanzania - United Republic of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TH','Thailand');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TL','Timor-Leste');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TG','Togo');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TK','Tokelau');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TO','Tonga');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TT','Trinidad and Tobago');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TN','Tunisia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TR','Turkey');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TM','Turkmenistan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TC','Turks and Caicos Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('TV','Tuvalu');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('UG','Uganda');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('UA','Ukraine');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('AE','United Arab Emirates');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('GB','United Kingdom');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('US','United States');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('UY','Uruguay');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('UZ','Uzbekistan');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VU','Vanuatu');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VA','Vatican City');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VE','Venezuela - Bolivarian Rep. of');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VN','Viet Nam');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('VI','Virgin Islands (US)');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('WF','Wallis and Futuna Islands');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('PS','West Bank and Gaza Strip');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('EH','Western Sahara');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('YE','Yemen');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ZM','Zambia');
INSERT INTO Nazioni(codiceNazione, nomeNazione) VALUES ('ZW','Zimbabwe');